# Generated by Django 6.0.5 on 2026-05-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_description_en_restaurant_description_tr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_manually_open',
            field=models.BooleanField(default=True),
        ),
    ]
