# Generated by Django 6.0.5 on 2026-05-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0002_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tr', models.CharField(max_length=120)),
                ('name_en', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ['name_en'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='category',
            name='name_tr',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='description_tr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='title_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='title_tr',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='menuapp.ingredient'),
        ),
    ]
